{
    "openapi": "3.0.0",
    "info": {
        "title": "RentX Documentation",
        "description": "This is an API Rent",
        "version": "1.0.0",
        "contact": {
            "email": "matheuskiel@fiorifer.com.br"
        }
    },
    "components": {
        "securitySchemes": {
            "BasicAuth": {
                "type": "http",
                "scheme": "basic"
            },
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer"
            },
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "apiKey"
            }
        }
    },
    "security": [
        {
            "BasicAuth": []
        },
        {
            "BearerAuth": []
        },
        {
            "ApiKeyAuth": []
        }
    ],
    "paths": {
        "/sessions": {
            "post": {
                "tags": [
                    "Session"
                ],
                "summary": "Create a session",
                "description": "Create a new session",
                "security": [],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Session/Create"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Session/Response"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "E-mail or password incorrect"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/categories": {
            "post": {
                "tags": [
                    "Category"
                ],
                "summary": "Create a category",
                "description": "Create a new category",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Category/Create"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Category already exists"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            },
            "get": {
                "tags": [
                    "Category"
                ],
                "summary": "List categories",
                "description": "List all categories",
                "security": [],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Category/List"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/categories/import": {
            "post": {
                "tags": [
                    "Category"
                ],
                "summary": "Upload categories",
                "description": "Upload new categories",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/specifications": {
            "post": {
                "tags": [
                    "Specification"
                ],
                "summary": "Create a specification",
                "description": "Create a new specification",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Specification/Create"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Specification already exists"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            },
            "get": {
                "tags": [
                    "Specification"
                ],
                "summary": "List specifications",
                "description": "List all specifications",
                "security": [],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Specification/List"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/users": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Create a user",
                "description": "Create a new user",
                "security": [],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/User/Create"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "User already exists"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/users/avatar": {
            "patch": {
                "tags": [
                    "User"
                ],
                "summary": "Upload user avatar",
                "description": "Upload user avatar",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "avatar": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/cars": {
            "post": {
                "tags": [
                    "Car"
                ],
                "summary": "Create a car",
                "description": "Create a new car",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Car/Create"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Car already exists"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/cars/available": {
            "get": {
                "tags": [
                    "Car"
                ],
                "summary": "List available cars",
                "description": "List all available cars",
                "security": [],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Car/ListAvailable"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/cars/specifications/{car_id}": {
            "post": {
                "tags": [
                    "Car"
                ],
                "summary": "Create a car specification",
                "description": "Create a new car specification",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "car_id",
                        "description": "car ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Car/Specification"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Car already exists"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/cars/images/{car_id}": {
            "post": {
                "tags": [
                    "Car"
                ],
                "summary": "Create a car image",
                "description": "Create a new car image",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "car_id",
                        "description": "car ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "images": {
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "format": "binary"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Car does not exists"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/rentals": {
            "post": {
                "tags": [
                    "Rental"
                ],
                "summary": "Create a rental",
                "description": "Create a new rental",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Rental/Create"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Rental/Created"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid params",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            },
                                            "example": {
                                                "message": "Car is unavailable"
                                            }
                                        },
                                        {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            },
                                            "example": {
                                                "message": "There is a rental in progress for user"
                                            }
                                        },
                                        {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            },
                                            "example": {
                                                "message": "The rental must have an minimun of 24 hours"
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/rentals/devolution/{id}": {
            "post": {
                "tags": [
                    "Rental"
                ],
                "summary": "Devolution of a rental",
                "description": "Devolution of a rental",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "description": "rental ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Rental/Devolution"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid params",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            },
                                            "example": {
                                                "message": "Rental does not exists"
                                            }
                                        },
                                        {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            },
                                            "example": {
                                                "message": "Car does not exists"
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/rentals/user": {
            "get": {
                "tags": [
                    "Rental"
                ],
                "summary": "Get user rentals",
                "description": "Get user rentals",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Rental/List"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid params",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            },
                                            "example": {
                                                "message": "Invalid token"
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/password/forgot": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Forgot password",
                "description": "Send e-mail to user with link to forgot password",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "email": "admin@rentx.com.br"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "User does not exists"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        }
    },
    "definitions": {
        "Specification": {
            "Create": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    }
                },
                "example": {
                    "name": "Alfa Romeo MiTo Specs",
                    "description": "Petrol Engine MiTo 0.9 Turbo TwinAir 85HP S&S Distinctive Specs; Year 2011; Horsepower 85; Engine Capacity 875cm3"
                }
            },
            "List": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "created_at": {
                            "type": "string"
                        }
                    }
                },
                "example": [
                    {
                        "id": "51bd7f19-820a-46fa-9c62-a2bac707176c",
                        "name": "Alfa Romeo MiTo Specs",
                        "description": "Petrol Engine MiTo 0.9 Turbo TwinAir 85HP S&S Distinctive Specs; Year 2011; Horsepower 85; Engine Capacity 875cm3",
                        "created_at": "2021-12-13T14:34:05.823Z"
                    }
                ]
            }
        },
        "Category": {
            "Create": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    }
                },
                "example": {
                    "name": "SUV",
                    "description": "What is an SUV? The acronym SUV stands for Sport Utility Vehicle -- that is, sport utility vehicle. SUVs tend to have a large size, in addition to a spacious interior and the possibility of traveling in and out of the city."
                }
            },
            "List": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "created_at": {
                            "type": "string"
                        }
                    }
                },
                "example": [
                    {
                        "id": "bfbb138a-1507-4502-8cf2-e88b8ab005fb",
                        "name": "SUV",
                        "description": "What is an SUV? The acronym SUV stands for Sport Utility Vehicle -- that is, sport utility vehicle. SUVs tend to have a large size, in addition to a spacious interior and the possibility of traveling in and out of the city.",
                        "created_at": "2021-12-13T14:33:37.356Z"
                    }
                ]
            }
        },
        "User": {
            "Create": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "driver_license": {
                        "type": "string"
                    }
                },
                "example": {
                    "name": "Matheus Kielkowski",
                    "email": "matheuskiel6@fiorifer.com.br",
                    "password": "12345",
                    "driver_license": "12345"
                }
            }
        },
        "Session": {
            "Create": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                },
                "example": {
                    "email": "admin@rentx.com.br",
                    "password": "admin"
                }
            },
            "Response": {
                "type": "object",
                "properties": {
                    "user": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string"
                            }
                        }
                    },
                    "token": "string"
                },
                "example": {
                    "user": {
                        "name": "Matheus Kielkowski",
                        "email": "matheuskiel6@fiorifer.com.br"
                    },
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDM5ODg3NTMsImV4cCI6MTY0NDA3NTE1Mywic3ViIjoiYzdjYjUyMWMtZTMwYS00MTQzLTk2MWMtNWJhYTNmMDQyN2ExIn0.WrvqAIeDbUMTJCN4zCGhccfF0_ReTai0E_m6uPJ2-04"
                }
            }
        },
        "Car": {
            "Create": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "daily_rate": {
                        "type": "number"
                    },
                    "license_plate": {
                        "type": "string"
                    },
                    "fine_amount": {
                        "type": "number"
                    },
                    "brand": {
                        "type": "string"
                    },
                    "category_id": {
                        "type": "string"
                    }
                },
                "example": {
                    "name": "Subaru Impreza",
                    "description": "The Subaru Impreza is a compact car manufactured since 1992 by Subaru, — the automobile division of Japan's Fuji Heavy Industries.",
                    "daily_rate": 100,
                    "license_plate": "XXXX-XX",
                    "fine_amount": 100,
                    "brand": "Subaru",
                    "category_id": "e42e6d7a-59fc-47e4-b850-7e1ae6874ab2"
                }
            },
            "ListAvailable": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "daily_rate": {
                            "type": "number"
                        },
                        "license_plate": {
                            "type": "string"
                        },
                        "fine_amount": {
                            "type": "number"
                        },
                        "brand": {
                            "type": "string"
                        },
                        "category_id": {
                            "type": "string"
                        },
                        "created_at": {
                            "type": "string"
                        }
                    }
                },
                "example": [
                    {
                        "id": "f4aeb30b-b380-4f29-a494-b2e3ec37645a",
                        "name": "Subaru Impreza",
                        "description": "The Subaru Impreza is a compact car manufactured since 1992 by Subaru, — the automobile division of Japan's Fuji Heavy Industries.",
                        "daily_rate": 100,
                        "license_plate": "XXXX-XX",
                        "fine_amount": 100,
                        "brand": "Subaru",
                        "category_id": "e42e6d7a-59fc-47e4-b850-7e1ae6874ab2",
                        "created_at": "2022-02-03T14:52:30.305Z"
                    }
                ]
            },
            "Specification": {
                "type": "object",
                "properties": {
                    "specifications_id": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "example": {
                    "specifications_id": [
                        "8609f28d-1c60-42a1-a907-41df7d0c8b41"
                    ]
                }
            }
        },
        "Rental": {
            "Create": {
                "type": "object",
                "properties": {
                    "car_id": {
                        "type": "string"
                    },
                    "expected_return_date": {
                        "type": "string"
                    }
                },
                "example": {
                    "car_id": "f4aeb30b-b380-4f29-a494-b2e3ec37645a",
                    "expected_return_date": "2022-03-19T13:58:44.750Z"
                }
            },
            "Created": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "car_id": {
                        "type": "string"
                    },
                    "user_id": {
                        "type": "string"
                    },
                    "expected_return_date": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "example": {
                    "id": "1fa5195e-ff85-4d9c-b032-361796289b5c",
                    "car_id": "59526d25-5af9-4c4f-9b05-02c4007a33fe",
                    "user_id": "5f25b613-4a26-49d9-8fbb-39b616a47797",
                    "expected_return_date": "2022-03-19T13:58:44.750Z",
                    "created_at": "2022-03-18T13:58:44.819Z",
                    "updated_at": "2022-03-18T13:58:44.819Z"
                }
            },
            "Devolution": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "car_id": {
                        "type": "string"
                    },
                    "user_id": {
                        "type": "string"
                    },
                    "start_date": {
                        "type": "string"
                    },
                    "end_date": {
                        "type": "string"
                    },
                    "expected_return_date": {
                        "type": "string"
                    },
                    "total": {
                        "type": "number"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "example": {
                    "id": "6b9c47b8-a4d2-4705-aac4-d7e93bf9d6c0",
                    "car_id": "7ed163a7-2b85-43b2-a1f6-d56ca0d687d7",
                    "user_id": "5f25b613-4a26-49d9-8fbb-39b616a47797",
                    "start_date": "2022-04-08T17:12:32.843Z",
                    "end_date": "2022-04-14T02:31:46.859Z",
                    "expected_return_date": "2022-04-09T17:12:32.762Z",
                    "total": 500,
                    "created_at": "2022-04-08T17:12:32.843Z",
                    "updated_at": "2022-04-08T17:13:00.436Z"
                }
            },
            "List": {
                "type": "array",
                "items": {
                    "id": {
                        "type": "string"
                    },
                    "car_id": {
                        "type": "string"
                    },
                    "user_id": {
                        "type": "string"
                    },
                    "start_date": {
                        "type": "string"
                    },
                    "end_date": {
                        "type": "string"
                    },
                    "expected_return_date": {
                        "type": "string"
                    },
                    "total": {
                        "type": "number"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    },
                    "car": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "available": {
                                "type": "boolean"
                            },
                            "name": {
                                "type": "string"
                            },
                            "description": {
                                "type": "string"
                            },
                            "daily_rate": {
                                "type": "number"
                            },
                            "license_plate": {
                                "type": "string"
                            },
                            "fine_amount": {
                                "type": "number"
                            },
                            "brand": {
                                "type": "string"
                            },
                            "category_id": {
                                "type": "string"
                            },
                            "created_at": {
                                "type": "string"
                            }
                        }
                    }
                },
                "example": [
                    {
                        "id": "6b9c47b8-a4d2-4705-aac4-d7e93bf9d6c0",
                        "car_id": "7ed163a7-2b85-43b2-a1f6-d56ca0d687d7",
                        "user_id": "5f25b613-4a26-49d9-8fbb-39b616a47797",
                        "start_date": "2022-04-08T17:12:32.843Z",
                        "end_date": "2022-04-14T02:37:07.964Z",
                        "expected_return_date": "2022-04-09T17:12:32.762Z",
                        "total": "500",
                        "created_at": "2022-04-08T17:12:32.843Z",
                        "updated_at": "2022-04-14T02:37:07.969Z",
                        "car": {
                            "id": "7ed163a7-2b85-43b2-a1f6-d56ca0d687d7",
                            "available": true,
                            "name": "Subaru Impreza",
                            "description": "The Subaru Impreza is a compact car manufactured since 1992 by Subaru, — the automobile division of Japan's Fuji Heavy Industries.",
                            "daily_rate": "100",
                            "license_plate": "XXXX-XX",
                            "fine_amount": "100",
                            "brand": "Subaru",
                            "category_id": "e42e6d7a-59fc-47e4-b850-7e1ae6874ab2",
                            "created_at": "2022-03-15T14:29:50.472Z"
                        }
                    }
                ]
            }
        }
    }
}